// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiB7JWrXplW7r3ru6FdRgh6ahfG7y1pw',
    appId: '1:587569767857:web:fa19b2eb68161dc94ac990',
    messagingSenderId: '587569767857',
    projectId: 'metafit-e277d',
    authDomain: 'metafit-e277d.firebaseapp.com',
    storageBucket: 'metafit-e277d.firebasestorage.app',
    measurementId: 'G-E86KN0ERXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJW5bEM0niZAFSJ1Mux8Kl91PuTJCMp7c',
    appId: '1:587569767857:android:c9b3dff938b877f64ac990',
    messagingSenderId: '587569767857',
    projectId: 'metafit-e277d',
    storageBucket: 'metafit-e277d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-4oZaH2Qbx9tpVjF0_fFjizApj3JbiA',
    appId: '1:587569767857:ios:528c6a4791a688d44ac990',
    messagingSenderId: '587569767857',
    projectId: 'metafit-e277d',
    storageBucket: 'metafit-e277d.firebasestorage.app',
    iosBundleId: 'com.metaf.metafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-4oZaH2Qbx9tpVjF0_fFjizApj3JbiA',
    appId: '1:587569767857:ios:528c6a4791a688d44ac990',
    messagingSenderId: '587569767857',
    projectId: 'metafit-e277d',
    storageBucket: 'metafit-e277d.firebasestorage.app',
    iosBundleId: 'com.metaf.metafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNiB7JWrXplW7r3ru6FdRgh6ahfG7y1pw',
    appId: '1:587569767857:web:302cc95d1a6197584ac990',
    messagingSenderId: '587569767857',
    projectId: 'metafit-e277d',
    authDomain: 'metafit-e277d.firebaseapp.com',
    storageBucket: 'metafit-e277d.firebasestorage.app',
    measurementId: 'G-5ZXQDTYW1V',
  );
}
